---
apiVersion: v1
kind: Namespace
metadata:
  name: wjru-ns
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: shopping-site-replica-ctrl
  namespace: wjru-ns
spec:
  replicas: 2
  selector:
    app: shopping-app
  template:
    metadata:
      name: shopping-site-pod
      namespace: wjru-ns
      labels:
        app: shopping-app
    spec:
      containers:
        - name: shopping-app-container
          image: madandevops2024/shoppingsite
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-site-lb-svc
  namespace: wjru-ns
spec:
  type: LoadBalancer
  selector:
    app: shopping-app #Pod label which we have created under labels
  ports:
    - port: 80
      targetPort: 8080
---

