---
apiVersion: v1
kind: Service
metadata:
  name: shopping-site-nodeport-svc
spec:
  type: NodePort
  selector:
    app: shopping-app #Pod label which we have created under labels
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30100
